name: Flomo Reminder

jobs:
  run_flomo_reminder:
    name: Run Flomo Reminder
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm install
      - env:
          FLOMO_AUTHORIZATION: ${{ secrets.FLOMO_AUTHORIZATION }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
        run: npm start
